# Site settings
title: Jaehyeon Nam
tagline: ""
description: Jaehyeon Nam
browser_title: "hi <3"
url: https://njh961.github.io
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

author:
  name: Jaehyeon Nam
  korean_name: 남재현
  email: njh961@gmail.com
  github: njh961

github:
  repo: https://github.com/njh961/njh961.github.io
